application: cppbash
version: 1
runtime: python
api_version: 1

handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/(.*)
- url: /static
  static_dir: static
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /_ah/queue/deferred
  script: main.py
  login: admin
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
- url: /review.*
  script: main.py
  login: required
- url: /.*
  script: main.py

admin_console:
  pages:
  - name: Appstats
    url: /stats
